### ISSUE TITLE
Invalid link in format bump wiki

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/swupd-server#110]
On the wiki page: https://github.com/clearlinux/swupd-server/wiki/Format-Bumps, the reference to https://clearlinux.org/documentation/mixer.html is invalid. The correct link should be: https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer

**Comment by phmccarty** [comment]
Thank you, Tom. I updated the wiki page.
