### ISSUE TITLE
No certificate check in packfsck.pl

### ISSUE THREAD

**Issue by johnandersen777** [clearlinux/swupd-server#29]
I'm not clear on what `packfsck.pl` is for, but I don't think it should be using `--no-check-certificate` no matter what it is.

https://github.com/clearlinux/swupd-server/blob/master/packfsck.pl#L10

**Comment by phmccarty** [comment]
The script can be used for validating pack content, since it cross-references the bundle manifests. Currently, it only checks `os-core` but could be made generic to validate any/all packs.

**Comment by phmccarty** [comment]
Fix merged in 490326f.
