### ISSUE TITLE
xattr mismatch in swupd_make_pack delta.c

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-server#35]
I'm building a delta between two local Ostro OS versions where only Smack xattrs are set on files.

swupd_make_pack fails with:
| Delta application resulted in xattrs mismatch.
| /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/image//102714550/full//etc/group->/fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/image//102715200/full//etc/group via diff /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/www//102715200/delta/.102714550-102715200-b44018c88fb9d6c7542c6d25372fc9130d394ce25456e787d289705af0be75b1 yielded /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/www//102715200/delta/.102714550-102715200-b44018c88fb9d6c7542c6d25372fc9130d394ce25456e787d289705af0be75b1.testnewfile
|   0.069 0.014 ../../../../../../workspace/sources/swupd-server-native/src/delta.c:107 | /etc/group                        | Delta xattrs mismatch:    | /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/image//102714550/full//etc/group->/fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/image//102715200/full//etc/group via diff /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/www//102715200/delta/.102714550-102715200-b44018c88fb9d6c7542c6d25372fc9130d394ce25456e787d289705af0be75b1 yielded /fast/build/ostro/x86/tmp-glibc/deploy/swupd/qemux86/ostro-image-swupd/www//102715200/delta/.102714550-102715200-b44018c88fb9d6c7542c6d25372fc9130d394ce25456e787d289705af0be75b1.testnewfile
| swupd_make_pack: ../../../../../../workspace/sources/swupd-server-native/src/delta.c:108: __create_delta: Assertion `0' failed.

The original and the modified /etc/group both have security.SMACK64="System::Shared".

delta/.102714550-102715200-b44018c88fb9d6c7542c6d25372fc9130d394ce25456e787d289705af0be75b1.testnewfile does not have that xattr set.

How are xattrs expected to be handled? In this case, swupd-server and swupd-client must copy the xattr from the original file to the patched file. Are they doing that? It doesn't seem to happen (or isn't working) for this .testnewfile.

Note that this case only occurs when xattrs are identical. Ostro OS uses IMA to hash the file content in the security.ima xattr. When that is active, swupd-server will see different xattrs each time a file content changes and thus will never calculate deltas. I'm just taking a note of that here in case that others try to reproduce this with unmodified Ostro OS: use DISTRO_FEATURES_remove = "ima" to trigger this issue here.

Regarding priority of this issue: if it is easy to fix, let's fix it, but if it requires a considerable amount of work, then let's wait until we know whether Ostro OS will continue to use Smack.

**Comment by pohly** [comment]
Fix is available, please merge.

**Comment by phmccarty** [comment]
Fixed in release v3.3.0.
