### ISSUE TITLE
v3.6.1 not tagged

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-server#74]
According to 330bede498b, 3.6.1 was released, but there is no tag for it.

**Comment by matthewrsj** [comment]
I'm seeing https://github.com/clearlinux/swupd-server/tree/v3.6.1 point to the right commit.

**Comment by pohly** [comment]
Right, the tag exists. I was fooled by "git fetch origin" fetching only the v3.6.0 tag, but not v3.6.1. An explicit "git fetch --tags" was needed.

**Comment by phmccarty** [comment]
Right, it looks like v3.6.1 was tagged, but the tagged commit is not on the master branch.

@matthewrsj Can you merge that commit to master? I always find it helpful to check git history before releasing to ensure I have tagged the correct commit.

**Comment by phmccarty** [comment]
Actually, looking more closely at the git history, the wrong commit was tagged for v3.6.1. There are in fact no changes (aside from the version bump) in v3.6.1 compared to v3.6.0.

@matthewrsj Can you cut a new release with the latest changes from master?

Edit: this explains why I am still seeing the 750 permissions on delta/ and staged/ within the packs with the v3.6.1 release.

**Comment by matthewrsj** [comment]
I'm a little confused about what happened, but it looks like making a new release will fix the issue. I see that the v3.6.1 release does not include the changes I thought it did.

**Comment by phmccarty** [comment]
The latest release commit is on master, so we can resolve this again.
