### ISSUE TITLE
existing file not reused?

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-server#88]
I'm writing some tests for meta-swupd and noticed something odd:

```
$ ls -l tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/*/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar
-rw-r--r-- 1 pohly pohly 197 Oct  6 11:30 tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/10/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar
-rw-r--r-- 1 pohly pohly 220 Oct  6 11:33 tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/20/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar

$ grep 28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062 tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/20/Manifest.full
F.C.	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/etc/default/usbd
F.C.	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/etc/ld.so.conf
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/email/mime/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/lib2to3/tests/data/fixers/myfixes/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/pydoc_data/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/sqlite3/test/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/tkinter/test/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/tkinter/test/test_tkinter/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/tkinter/test/test_ttk/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/lib/python3.5/urllib/__init__.py
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/share/clear/bundles/os-core
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	10	/usr/share/mime/icons
F...	28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062	20	/usr/bin/modify_files_was_added
```

All these files are empty and have the same attributes, so it's not surprising that they have the same hash. But why is the file hashed again when preparing the update for version 20? Shouldn't there only be one copy under 10/files and that last entry in the Manifest.full point to that?

**Comment by pohly** [comment]
/usr/bin/modify_files_was_added has to be listed with version 20 because that indicates to swupd-client that the entry is new in that release. That 20/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar then gets created anew is a consequence of the current design, because the client expects it there.

The enhancement would be to detect this case, then use hardlinking or symlinking on the server side to avoid the duplication of effort (creating the archive) and resources (storing another copy).

**Comment by icarus-sparry** [comment]
Many modern filesystems, such as btrfs and zfs have support for consolidation of identical data blocks. This allows a generic solution to reducing the resources, rather than a swupd-server specific one. I am not sure how we know in advance that a file is identical to an existing one, so we would still need to do most of the work of creating the archive regardless.

**Comment by pohly** [comment]
@icarus-sparry it is the other way around: 10/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar can be reused instead of creating 20/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar anew because the hash guarantees that the content must be the same as the corresponding file in the 20 build in all relevant attributes (content, ownership, permissions, etc.). Otherwise the hash would be different.

In fact, in my test the actual .tar files are different:
```
-rw-r--r-- 1 pohly pohly 197 Oct 24 09:02 tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/10/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar
-rw-r--r-- 1 pohly pohly 220 Oct 24 09:07 tmp-glibc/deploy/swupd/intel-corei7-64/refkit-image-update-swupd/www/20/files/28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062.tar
```

It's probably because the tar command archives also some additional attributes (like time stamps) which don't matter for swupd although they change between builds.

This example therefore shows that relying on de-duplication in the filesystem or the content delivery network is less effective than de-duplicating at the semantic level inside swupd-server itself - it wouldn't work in this case, while it could be made to work inside swupd-server.

**Comment by pohly** [comment]
BTW, as far as I am concerned, this issue can be closed because it has been clarified. I'll leave it to you whether you want to keep it open to track some future enhancement.

**Comment by matthewrsj** [comment]
Closing as manual de-duplication is not a priority for us right now.
