### ISSUE TITLE
Content and Version URL

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-server#92]
This might seem like a silly question but can someone explain the details behind each of these URL's? Is there any harm in having them both point to the content URL? If content and version URL both contain the latest update what advantage does version URL provide?

**Comment by phmccarty** [comment]
> Is there any harm in having them both point to the content URL?

There is no harm in doing so. The directory hierarchies expected at the content URL versus version URL do not overlap, so they can coexist at the same location.

> If content and version URL both contain the latest update what advantage does version URL provide?

The version URL must host the `version/formatN` directory hierarchy, with each `formatN` directory containing the `latest` file. The content of each `latest` file can be any version number that swupd-server has built content for. So, the benefit of having the separation of content/version is when you want to select what `latest` should be. It might not be the latest content hosted at the content URL.

**Comment by aaronovz1** [comment]
So version URL doesn't need to host any of the `N` folders? In what circumstance would you not have the latest content hosted but have `latest` point to it? Sorry, just trying to wrap my head around how I should deploying/hosting the updates.

**Comment by phmccarty** [comment]
> So version URL doesn't need to host any of the N folders?

Correct, the `N` directories are only needed at the content URL.

> In what circumstance would you not have the latest content hosted but have latest point to it?

If `latest` points to content for a build that is not hosted, then that is indeed a problem :-) The case I described is kind of the reverse of that, where you have built one or more *candidate* latest builds, but the `latest` file still points to an older build.

A concrete example: The `latest` file contains version 100, and builds 10 through 100 are hosted at the content URL. Then I build 110, publish the content, but I decide not to bump `latest` to 110, say if some test failures are encountered. So, `latest` still contains 100. Then I build 120, and it's a good build, so I bump `latest` to 120.

**Comment by aaronovz1** [comment]
Ok I understand it better now. In our CI system the only time we publish updates is once internal testing has given a pass, then someone manually updates a variable (OS_VERSION in Yocto environment), this then causes swupd to called to generate the updates. We use two pipelines and deployment locations, one for testing and one for production (kind of like master vs. dev branch). We only merge changes into production once validation has passed.

So in our setup `latest` always points to the latest published content. I'm not sure if this is the best/common practice but it does allow us to have two update pipelines so things don't accidentally slip into production. This is why currently having both URL's point to the content location is working fine at the moment.

**Comment by phmccarty** [comment]
I think the only thing to be concerned with is for `latest` to always point to the version you intend it to. The split content/version URL scheme is pretty flexible and can accomodate different setups.

Another example use case is on the client side, when a user does not want to update to the latest version as specified at the configured version URL, but to an older (or newer) version. Using the example from my previous comment, instead of updating from 100 to 120 (latest), the user wants to update to 110. They can do so by first creating a version directory hierarchy somewhere on their local system, say `/tmp/update/version/format1`, and running `echo 110 > /tmp/update/version/format1/latest`. Then they can run their update from 100 to 110 with `swupd update -v file:///tmp/update`.

**Comment by aaronovz1** [comment]
Thanks for clarifying. I think how I have things setup should work. We're using this on an embedded device so there is no user interaction where they can decide what to update. Devices always update to latest available.
