### ISSUE TITLE
Lingering renames in manifests after target deleted

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-server#93]
In the case where renames are detected and included in a manifest (i.e. version 10) for a bundle, then the target file is later deleted from that bundle, the renamed-from file will hang around with no corresponding target.

These renamed-from files (`.d.r`) should have their hashes set to all zeros and turned into a pure delete when the matching hash does not exist in the manifest.

**Comment by phmccarty** [comment]
This bug is similar to #94, which affects the renamed-to files (instead of renamed-from).
