### ISSUE TITLE
Orphaned renames in manifests after pruning

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-server#94]
When rename detection is enabled, the rename detection step occurs before the pruning step, but the pruning step has no knowledge of renamed files. This can result in renamed-to files being orphaned.

To resolve this, renamed-to files should be unmarked as renamed (i.e. lose their `r` flag) in the event their corresponding renamed-from files are pruned.

**Comment by matthewrsj** [comment]
I'm actually not seeing where old rename-from files would be pruned. Old deleted files are removed from the manifest in [remove_old_deleted_files()](https://github.com/clearlinux/swupd-server/blob/master/src/manifest.c#L971) but the files need to be the same filename and both need to be marked as deleted. With renames only the renamed-from file will be marked as deleted and obviously the two files will have different filenames.

[prune_manifest()](https://github.com/clearlinux/swupd-server/blob/master/src/manifest.c#L1035) only removes config files, debuginfo files (if configured to do so), and deleted boot files (which will be handled via the ghosting logic when #97 is merged).

**Comment by matthewrsj** [comment]
We are seeing renamed-from files going missing because kernel files are being pruned. #97 will fix that.
